### ISSUE TITLE
how to run this code?

### ISSUE THREAD

**Issue by shubham-dua** [jacks205/Spell-Check#1]
when i run the __init__.py file the following error is generated:

Traceback (most recent call last):
  File "C:\Python27\__init__.py", line 11, in <module>
    main()
  File "C:\Python27\__init__.py", line 6, in main
    spellchk.run(sys.argv[1])
IndexError: list index out of range

**Comment by jacks205** [comment]
If you take a look at [`spellcheck.py`](https://github.com/jacks205/Spell-Check/blob/master/spellcheck.py) it imports the Unix list of words you can find at `/usr/share/dict/words`, which is explained [here](https://en.wikipedia.org/wiki/Words_(Unix)). Seeing you're on Windows, you can find that list online, or create it yourself and replace the import path in `__init__.py` to the path to your file. 

Before:
```
spellchk = SpellCheck('/usr/share/dict/words')
```
After:
```
spellchk = SpellCheck("C:\Users\your\path\words.txt")
```

Once you do that, run it with either a `0` or `1` for the mode. `0` allows  you to input your own misspelled words, while `1` generates misspelled words.

`python __init__.py 0`

I've attached a sample list of words you can use: [words.txt](https://github.com/jacks205/Spell-Check/files/825920/words.txt)
